### ISSUE TITLE
compressing http and https into //

### ISSUE THREAD

**Issue by umbreak** [mohiva/play-html-compressor#33]
I guess is a correct behavior of the plugin to remove the protocol from the URL (https://google.com -> //google.com). Then the browser will decide to use either http or https (wether your current website is http or https).

However, there are some cases where I need to force an https link or an http link (`_target="blank"`) cause the other port is simply not listening and the url won't work.

**Comment by akkie** [comment]
The documentation points out that a user defined implementation of the filter could be used. Doesn't this work for you?

**Comment by umbreak** [comment]
You are right. That will work. Thanks!

**Comment by umbreak** [comment]
Well, the documentation is wrong. For Java (and PLay 2.3.x) `CustomHTMLCompressorFilter` should implement  `HTMLCompressorBuilder builder()`

**Comment by akkie** [comment]
The documentation describes the custom implementation from the [test](https://github.com/mohiva/play-html-compressor/blob/master/test/com/mohiva/play/htmlcompressor/java/HTMLCompressorFilterTest.java#L243). And I think this compiles and works as expected. But if not it would be nice if you could create a pull request.

**Comment by umbreak** [comment]
Hum...the IDE marks it as an error but If I run the project it works. Weird.
