### ISSUE TITLE
Play 2.4 binary incompatibility 

### ISSUE THREAD

**Issue by raelg** [mohiva/play-html-compressor#35]
Hi,

I've just updated an app to Play 2.4 and there is a binary incompatibility from a change introduced in the copy method of ResponseHeader 
https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.mvc.ResponseHeader 

It appears the addition of a new default argument is incompatible since the compiled code references a generated method which no longer exists. Unfortunately this issues exists because of how default arguments seem to be implemented - I would have expected this change would be non-breaking. 

The error I get is: `java.lang.NoSuchMethodError: play.api.mvc.ResponseHeader.copy(ILscala/collection/immutable/Map;)Lplay/api/mvc/ResponseHeader;`

Any plans to release a new version for 2.4? 

Thanks.

**Comment by akkie** [comment]
Do you use the 3.0-SNAPSHOT allerdings?

**Comment by akkie** [comment]
Sorry, I thougt this was the Silhouette project. There is currently no SNAPSHOT version for this project. It would be nice if you could create a pull request.

**Comment by akkie** [comment]
Fixed with https://github.com/mohiva/play-html-compressor/pull/36
