### ISSUE TITLE
HTML compression for chunked encoding

### ISSUE THREAD

**Issue by mantsak** [mohiva/play-html-compressor#39]
Hello mohiva,

this is not a bug, just a question. I had an issue recently on another project that producs `chunked` encoding. The issue there is at https://github.com/brikis98/ping-play/issues/15

I looked into your code and the closed issues, but did not find a reason why those `chunked` responses are disabled from the HTMLCompressorFilter. Obiously, the html compression can only be done through the last closure `>` tag and always wait for the next `>` from the HtmlStream / Enumerator.

Thanks,

Manolis

**Comment by akkie** [comment]
Please see https://github.com/mohiva/play-html-compressor/pull/31
