### ISSUE TITLE
Use with Dependency Injection

### ISSUE THREAD

**Issue by neilchaudhuri** [mohiva/play-html-compressor#43]
The README indicates how to use play-html-compressor by working with Global. As Play tarnsitions away from global state, how can we use play-html-compressor to utilize dependency injection with our chosen framework (Scaldi in my case)?

Thanks.

**Comment by akkie** [comment]
The readme isn't updated for Play 2.4 yet. But you can use this filter as [every other filter](https://www.playframework.com/documentation/2.4.x/ScalaHttpFilters#Using-filters) too.

**Comment by akkie** [comment]
I've rewritten the module to work completely without global state and I've updated the documentation.
