### ISSUE TITLE
Not working with Play 2.5

### ISSUE THREAD

**Issue by ptrlaszlo** [mohiva/play-html-compressor#46]
HTML compressor is not working with Play 2.5. Play is now using [Akka streams](https://playframework.com/documentation/2.5.x/Highlights25) with a modified [Result](https://www.playframework.com/documentation/2.5.x/api/scala/index.html#play.api.mvc.Result) class, which breaks html compressor 0.5.0

**Comment by akkie** [comment]
Yes I know. I'm very busy with the Silhouette library currently. A pull request would be very welcome!

**Comment by akkie** [comment]
Fixed with #47
