### ISSUE TITLE
Issue with absolute URL

### ISSUE THREAD

**Issue by 0xbaadf00d** [mohiva/play-html-compressor#52]
Hi,

we have an issue with your plugin: it remove trailling protocole on absolute URL.

**Without default HTML Compressor**

```html
<form class="form" action="https://secure.payzen.eu/vads-payment/" name="payzen_form" id="payzen_from">
</form>
```

**With default HTML Compressor**

```html
<form class="form" action="//secure.payzen.eu/vads-payment/" name="payzen_form" id="payzen_from">
</form>
```

The issue seem appear only with `activator stage|start`, not `activator run`
So, when the website is not on HTTPS, the form lead to a not working URL (The used  Payment Service Provider dont listen on HTTP)

Thanks

**Comment by akkie** [comment]
This is not really an issue. We can sadly not handle all use cases.

But, you can create your own HTML compressor as described in the docs and set:
```
setRemoveHttpsProtocol(false)
```

**Comment by 0xbaadf00d** [comment]
Thanks for the tips
