### ISSUE TITLE
Extend play.api.mvc.EssentialFilter

### ISSUE THREAD

**Issue by eximius313** [mohiva/play-html-compressor#56]
Since Play 2.5.4 we have a nice helper for creating filters: https://github.com/playframework/playframework/pull/6117

The point is, that filter must extend ```play.api.mvc.EssentialFilter```

Could you please make ```HTMLCompressorFilter``` and ```XMLCompressorFilter``` subclass of ```EssentialFilter```?

**Comment by akkie** [comment]
@eximius313 I'm not sure I understand you correct, but both classes are already a subclass of `EssentialFilter`.

```scala
abstract class CompressorFilter[C <: Compressor] extends Filter
```

And in Play:
```scala
trait Filter extends EssentialFilter
```

**Comment by eximius313** [comment]
@akkie in my previous try, it threw Class cast exception. Now it seems to work...
Thanks
