### ISSUE TITLE
HTMLCompressorFilter strips protocol

### ISSUE THREAD

**Issue by eximius313** [mohiva/play-html-compressor#57]
in the template I have:
```
<a target="_blank" rel="nofollow" href="http://test.com">http://test.com</a>
<a target="_blank" rel="nofollow" href="https://test.com">https://test.com</a>
```
without ```HTMLCompressorFilter``` it stays exactly the same, but with filter enabled it becomes:
```
<a target="_blank" rel="nofollow" href="//test.com">http://test.com</a>
<a target="_blank" rel="nofollow" href="//test.com">https://test.com</a>
```
which is bad because protocols (http/https) are changed

**Comment by eximius313** [comment]
I think this lines:
https://github.com/mohiva/play-html-compressor/blob/master/app/com/mohiva/play/htmlcompressor/HTMLCompressorFilter.scala#L62 
and
https://github.com/mohiva/play-html-compressor/blob/master/app/com/mohiva/play/htmlcompressor/HTMLCompressorFilter.scala#L63
cause the problem. I consider it as bad practice to set it to ```true``` as default

**Comment by akkie** [comment]
If the default filter doesn't work for you, you should create your own filter configuration. These days the most sites are either completely served over HTTP or over HTTPS. So in most cases this isn't an issue.

But, I will let the issue open. So that other users can vote about this feature. What do you think?

**Comment by 0xbaadf00d** [comment]
Already reported, the best workaround is to implemented you own custom class extended from default Html compressor and set to false protocol strip.

**Comment by akkie** [comment]
@0xbaadf00d Great idea! If anyone could create a pull request this would be awesome!

**Comment by eximius313** [comment]
@akkie but these are ```external``` urls! I have my site on ```https``` and external link works only with ```http```, but still is provided with ```//```. This is a serious problem.
@0xbaadf00d yup, possibility of configuration is always welcome (but still I consider this as a bug)

**Comment by 0xbaadf00d** [comment]
Is not an issue, in fact the base configuration not cover your needs. Create a custom class and use it.

```java
package filters;

import akka.stream.Materializer;
import com.googlecode.htmlcompressor.compressor.HtmlCompressor;
import com.mohiva.play.htmlcompressor.HTMLCompressorFilter;
import play.Environment;
import play.Mode;
import play.api.Configuration;

import javax.inject.Inject;
import javax.inject.Singleton;

/**
 * Add extra headers to all results.
 *
 * @author Thibault Meyer
 * @version 16.04.29
 * @since 16.04.29
 */
@Singleton
public class CustomHTMLCompressorFilter extends HTMLCompressorFilter {

    /**
     * Handle to the current application configuration.
     *
     * @since 16.04.29
     */
    private final Configuration configuration;

    /**
     * Handle to the current running environment.
     *
     * @since 16.04.29
     */
    private final Environment environment;

    /**
     * Handle to the {@code Materializer} object.
     *
     * @since 16.04.29
     */
    private final Materializer mat;

    /**
     * Build a default instance.
     *
     * @param configuration The current application configuration
     * @param environment   The current running environment
     * @param mat           The {@code Materializer} instance to use
     * @since 16.04.29
     */
    @Inject
    public CustomHTMLCompressorFilter(final Configuration configuration, final Environment environment, final Materializer mat) {
        this.configuration = configuration;
        this.environment = environment;
        this.mat = mat;
    }

    @Override
    public Configuration configuration() {
        return this.configuration;
    }

    @Override
    public HtmlCompressor compressor() {
        final HtmlCompressor compressor = new HtmlCompressor();
        if (environment.mode() == Mode.DEV) {
            compressor.setPreserveLineBreaks(true);
        }
        compressor.setRemoveComments(true);
        compressor.setRemoveIntertagSpaces(true);
        compressor.setRemoveHttpProtocol(false);
        compressor.setRemoveHttpsProtocol(false);
        return compressor;
    }

    @Override
    public Materializer mat() {
        return this.mat;
    }
}
```

**Comment by eximius313** [comment]
It's not that "base configuration not cover my needs".
I have a website on https://mywebsite.com which links to ```http://bash.org/``` (real example)
Now - look what happens when you try to access ```https://bash.org/``` (because of invalid ```//``` on my https site)

**Comment by akkie** [comment]
I'll close this as non-issue. We cannot cover every use case and with the current default config, a user saves the most space. I know this can be an issue for some sites but the default filter is now configurable and so it's easier adaptable.
